backup:
	cd .. && cd wms-environment/porrtinari/SL-BaseFoundation && rm -Rf node_modules
	cd .. && cd wms-environment/porrtinari/SL-WebFoundation && rm -Rf node_modules
	cd .. && cd wms-environment/porrtinari/SL-WMSPO && rm -Rf node_modules
	cd .. && cd wms-environment/porrtinari/SL-WMSPO-Learn && rm -Rf node_modules
	cd .. && cd wms-environment/Mobile/SL-WMSMobile && rm -Rf node_modules
	cd .. && cd wms-environment/Mobile/SL-WMSMobile-Learn && rm -Rf node_modules

	cp -vru * /destino
