cloneMobile:
	git clone totvstfs@vs-ssh.visualstudio.com:v3/totvstfs/SuiteLogistica/SL-WMSMobile
	
sdkManCommands:
	sdk list java
	sdk use java 8.0.275.open-adpt

androiRunNoNative:
	ionic cordova run android --no-native-run
	
androidRun:
	npm run android:run

criarApk:
    npm run android:build
    
espelhartTela:
    scrcpy
    
setarAndroidHome:
	ANDROID_HOME=ANDROID_HOME
	
Inspecionar:
    chrome://inspect/device
    
ionicPlatformBrowser:
	ionic cordova platform add browser
	ionic serve --cordova --platform=browser --configuration=local-browser
	
inspectChrome:
	chrome://inspect/#devices

configVsCode:
    file >>
    preferences >>
    filter import >>
    javascript preferences import = relative
    javascript preferences Quote  = single
    typescript preferences import = relative
    typescript preferences quote = single
    
    
