Atualizar:
	cd SL-BaseFoundation && git pull
	cd SL-WebFoundation && git pull
	cd SL-WMSPO && git pull

clone:
	git clone totvstfs@vs-ssh.visualstudio.com:v3/totvstfs/SuiteLogistica/SL-BaseFoundation
	git clone totvstfs@vs-ssh.visualstudio.com:v3/totvstfs/SuiteLogistica/SL-WebFoundation
	git clone totvstfs@vs-ssh.visualstudio.com:v3/totvstfs/SuiteLogistica/SL-WMSPO

